FROM container-registry.oracle.com/os/oraclelinux:9

COPY rpms/apiserver*.rpm /tmp/

RUN dnf install -y /tmp/*.rpm &&\
    dnf clean all && rm -rfv /var/cache/yum /tmp/* /LICENSES &&\
    ln -s /usr/share/licenses /LICENSES

FROM container-registry.oracle.com/os/oraclelinux:9-slim

RUN mkdir /code

COPY --from=0 /bin/apiserver /code/apiserver

COPY THIRD_PARTY_LICENSES.txt /usr/share/licenses/

COPY SECURITY.md /usr/share/licenses/

WORKDIR /code

ENV PATH="$PATH:/code"

ENTRYPOINT ["apiserver"]
