FROM container-registry.oracle.com/os/oraclelinux:9

COPY rpms/cni-plugin*.rpm /tmp/

RUN dnf install -y /tmp/*.rpm &&\
    dnf clean all && rm -rfv /var/cache/yum /tmp/* /LICENSES &&\
    ln -s /usr/share/licenses /LICENSES

FROM container-registry.oracle.com/os/oraclelinux:9-slim

RUN mkdir -m 777 -p /opt/cni/bin

COPY --from=0 /opt/cni/bin/cni-plugin-install /opt/cni/bin/cni-plugin-install
COPY --from=0 /opt/cni/bin/calico /opt/cni/bin/calico
COPY --from=0 /opt/cni/bin/calico-ipam /opt/cni/bin/calico-ipam

RUN ln -s /opt/cni/bin/cni-plugin-install /opt/cni/bin/install &&\
    cmp -s /opt/cni/bin/calico /opt/cni/bin/calico-ipam &&\
    ! cmp -s /opt/cni/bin/calico /opt/cni/bin/cni-plugin-install

COPY THIRD_PARTY_LICENSES.txt /usr/share/licenses/

COPY SECURITY.md /usr/share/licenses/

WORKDIR /opt/cni/bin

ENV PATH="$PATH:/opt/cni/bin"

CMD ["/opt/cni/bin/install"]
